---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "siddhi"
  namespace: "default"
  labels:
    app: "siddhi"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "siddhi"
  template:
    metadata:
      labels:
        app: "siddhi"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/cap1-339903/github.com/siddhishirdhankar/onlinevegetablesale@sha256:8a982165540782233eff637bb98fd77dbe5f7b1dbe97ca18af8a2bada4c08980"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "siddhi-hpa-ihoi"
  namespace: "default"
  labels:
    app: "siddhi"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "siddhi"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
