---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "onlinevegetablesale"
  namespace: "default"
  labels:
    app: "onlinevegetablesale"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "onlinevegetablesale"
  template:
    metadata:
      labels:
        app: "onlinevegetablesale"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/cap1-339903/github.com/siddhishirdhankar/onlinevegetablesale@sha256:43626753cc3e4d488c9c40582ad7117f80a892e1abe8291e9c8e7b0ae560f14a"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "onlinevegetablesale-hpa-x4og"
  namespace: "default"
  labels:
    app: "onlinevegetablesale"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "onlinevegetablesale"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
