---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ovsapp"
  namespace: "default"
  labels:
    app: "ovsapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ovsapp"
  template:
    metadata:
      labels:
        app: "ovsapp"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/cap1-339903/github.com/siddhishirdhankar/onlinevegetablesale@sha256:1ca3500d897d77e217a7b36195d580a98fbf6040d2b87f002c74ba941d3ca2ed"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ovsapp-hpa-lktw"
  namespace: "default"
  labels:
    app: "ovsapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ovsapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
