---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "siddhii"
  namespace: "default"
  labels:
    app: "siddhii"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "siddhii"
  template:
    metadata:
      labels:
        app: "siddhii"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/cap1-339903/github.com/siddhishirdhankar/onlinevegetablesale@sha256:2d88a5203263097c629c558655f186c8d2aad1e9e16a6acd17046f4bdd1fed7b"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "siddhii-hpa-1d3t"
  namespace: "default"
  labels:
    app: "siddhii"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "siddhii"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
